export enum NewBooks {
    Matthew =  'Mateus',
    Mark =  'Marcos',
    Luke =  'Lucas',
    John =  'João',
    Acts =  'Atos',
    Romans =  'Romanos',
    Corinthians =  'Coríntios',
    Galatians =  'Gálatas',
    Ephesians =  'Efésios',
    Philippians =  'Filipenses',
    Colossians =  'Colessenses',
    Thessalonians =  'Tessalonissenses',
    Timothy =  'Timóteo',
    Titus =  'Titos',
    Hebrews =  'Hebreus',
    James =  'Tiago',
    Peter =  'Pedro',
    Jude =  'Judas',
    Revelation =  'Apocalipse',
}