export enum OldBooks {
    Genesis = 'Gênesis',
    Exodus = 'Exôdus',
    Leviticus = 'Leviticus',
    Numbers = 'Numeros',
    Deuteronomy = 'Deuteronômio',
    Joshua = 'Josué',
    Judges = 'Juízes',
    Samuel = 'Samuel',
    Kings = 'Reis',
    Chronicles = 'Crônicas',
    Nehemiah = 'Neemias',
    Job = 'Jó',
    Psalm = 'Salmos',
    Proverbs = 'Provérbios',
    Ecclesiastes = 'Eclisiastes',
    Isaiah = 'Isaías',
    Jeremiah = 'Jeremias',
    Ezekiel = 'Ezequiel',
    Daniel = 'Daniel',
    Hosea = 'Oséas',
    Joel = 'Joel',
    Amos = 'Amós',
    Jonah = 'Jonas',
    Naum = 'Naum',
    Micah = 'Miqueias',
    Habakkuk = 'Habacuque',
    Zephaniah = 'Sofanias',
    Haggai = 'Ageu',
    Malachi = 'Malaquias',
    
}